version: '3'

services:
  client:
    build: ./client
    ports:
      - "8080:8080"
    volumes:
      - ./client:/app/client
      - /app/client/node_modules

  server:
    build: ./server
    ports:
      - "3000:3000"
    volumes:
      - ./server:/app/server
      - /app/server/node_modules

  db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=tenant_portal
    ports:
      - "42333:3306"
