version: '3'

services:
  client:
    build: ./client
    ports:
      - "8080:8080"
    volumes:
      - ./client:/client
      - /client/node_modules

  server:
    build: ./server
    ports:
      - "3000:3000"
    volumes:
      - ./server:/server
      - /server/node_modules

  db:
    image: mysql:latest
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_HOST=db
      - MYSQL_DATABASE=tenant_portal
      - MYSQL_USER=app_user
      - MYSQL_PASSWORD=password
    ports:
      - "42333:3306"
