exports.HTTP_STATUS = {
	OK: 200,
	CREATED: 201,
	BAD_REQUEST: 400,
	UNAUTHORIZED: 401,
	NOT_FOUND: 404,
	INTERNAL_SERVER_ERROR: 500,
};

exports.ERR_MESSAGES = {
	INVALID_ID: 'Invalid ID',
	USER_NOT_FOUND: 'User not found',
}